services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=test'
      - 'MYSQL_PASSWORD=root1234'
      - 'MYSQL_ROOT_PASSWORD=root1234'
      - 'MYSQL_USER=test'
    ports:
      - '3306:3306'