## Uncomment to add kubernetes route
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: template-service-java-springboot
#  namespace: template-service-java-springboot
#spec:
#  #  host must conform to DNS 952 subdomain conventions
#  host: "template-service-java-springboot-template-service-java-springboot-.dev-shubhamvarshney.io"
#  port:
#    targetPort: 8080
#  to:
#    kind: Service
#    name: template-service-java-springboot
#    weight: 100
#  tls:
#    termination: edge
#    insecureEdgeTerminationPolicy: Redirect
#  wildcardPolicy: None
#---